<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>

		<Title>Despro Framework Application</Title>
		<PackageId>Despro.Framework.Application</PackageId>
		<Product>Despro.Framework.Application</Product>

		<PackageTags>Despro Framework Application</PackageTags>
		<Description>Application Framework For Despro</Description>

		<Version>2.0.8</Version>

		<Authors>Despro Team</Authors>

		<PackageIcon>Framework.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<RepositoryUrl>https://github.com/Alireza-Gholiei/Despro.Framework.git</RepositoryUrl>

		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Framework.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>/</PackagePath>
		</None>
	</ItemGroup>


	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="14.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Despro.Framework.Base\Despro.Framework.Base.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="ApplicationExtensions\" />
	</ItemGroup>

</Project>
