<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>

		<Title>Despro Framework Infrastructure</Title>
		<PackageId>Despro.Framework.Infrastructure</PackageId>
		<Product>Despro.Framework.Infrastructure</Product>

		<PackageTags>Despro Framework Infrastructure</PackageTags>
		<Description>Infrastructure Framework For Despro</Description>

		<Version>2.1.5</Version>

		<Authors>Despro Team</Authors>

		<PackageIcon>Framework.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<RepositoryUrl>https://github.com/Alireza-Gholiei/Despro.Framework.git</RepositoryUrl>

		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Framework.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>/</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="MediatR" Version="14.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageReference Include="MongoDB.Driver" Version="3.9.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Despro.Framework.Base\Despro.Framework.Base.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="InfrastructureExtentisions\" />
	</ItemGroup>

</Project>
