<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Title>Despro Framework Base</Title>
		<PackageId>Despro.Framework.Base</PackageId>
		<Product>Despro.Framework.Base</Product>
		<PackageTags>Despro Framework Base</PackageTags>
		<Description>Base Framework For Despro</Description>
		<Authors>Despro Team</Authors>
		<PackageIcon>Framework.png</PackageIcon>
		<Version>2.1.0</Version>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RepositoryUrl>https://github.com/Alireza-Gholiei/Despro.Framework.git</RepositoryUrl>
		<NuGetAudit>false</NuGetAudit>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Framework.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Mapster" Version="7.4.0" />
		<PackageReference Include="MediatR" Version="14.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>
</Project>
