<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>

		<Title>Despro Framework Presentation</Title>
		<PackageId>Despro.Framework.Presentation</PackageId>
		<Product>Despro.Framework.Presentation</Product>

		<PackageTags>Despro Framework Presentation</PackageTags>
		<Description>Presentation Framework For Despro</Description>

		<Version>2.10.3</Version>

		<Authors>Despro Team</Authors>

		<PackageIcon>Framework.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<RepositoryUrl>https://github.com/Alireza-Gholiei/Despro.Framework.git</RepositoryUrl>

		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Framework.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>/</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Despro.Framework.Base\Despro.Framework.Base.csproj" />
	</ItemGroup>

</Project>
